name: "Terraform Destroy"

on:
  workflow_dispatch:
    inputs:
      confirm:
        type: choice
        required: true
        description: Do you wish to run terraform destroy?
        options: 
        - ''
        - 'no'
        - 'yes'
      message:
        description: Only "CONFIRM" will result in running this destroy plan
        required: true

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: List inputs
        run: | 
          echo "Input 1: ${{github.events.inputs.confirm}}"
          echo "Input 2: ${{github.events.inputs.message}}"
      - name: Terraform Destroy
        working-directory: ./terraform
        if: ${{github.events.inputs.confirm == 'yes' && github.events.inputs.message == 'CONFIRM'}}
        run: terraform destroy -auto-approve